### PR TITLE
Added zh-TW translation.

### PR DESCRIPTION
**Pull request by KaiLee2588**
I've added Traditional Chinese localization, based on both the en-US and the zh-CN strings.
Tested on OBS 29.0.2 with no display issues.

### CODE REVIEW

**Comment by phandasm** [comment]
Thanks!

**Comment by KaiLee2588** [comment]
> Thanks!
My pleasure, thank you for the development!
If able, I will love to be mentioned in the THANKS list.

**Comment by KaiLee2588** [comment]
> Thanks!

My pleasure, thank you for the development!
If able, I will love to be mentioned in the THANKS list.

**Comment by phandasm** [comment]
Oops, forgot to do that.
I've added you now.

**Pull request merged**
